version: '3'
services:
  consul:
    labels:
      consul: "bigip"
    command: "-server -bootstrap -node consul -advertise ${HOST_IP}"
    image: progrium/consul:latest
    container_name: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    environment:
      - HOST_IP
  registrator:
    labels:
      consul: "bigip"
    command: consul://consul:8500
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
