version: '3'
services:
  consul:
    labels:
      consul: "bigip"
    command: "-server -bootstrap -node consul -advertise ${HOST_IP} -config-file /etc/consul.d/config.json"
    image: progrium/consul:latest
    container_name: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
      - "8600:53/udp"
    volumes:
      - "./consul_watches_config.json:/etc/consul.d/config.json"
      - "./script_bigip_dns.sh:/tmp/script.sh"
    environment:
      - HOST_IP
  registrator:
    labels:
      consul: "bigip"
    command: consul://consul:8500
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
